### ISSUE TITLE
mix test fails

### ISSUE THREAD

**Issue by akeating** [slashdotdash/conduit#1]
```
18:03:43.094 [error] GenServer EventStore.Writer terminating
** (FunctionClauseError) no function clause matching in EventStore.Storage.QueryLatestEventId.handle_response/1
...
```
There were lots of warnings in the compile step.
Any insights?

**Comment by slashdotdash** [comment]
Sorry, I realise there isn't any help with getting started in the repo, as it's all in the book. I'll add this to the README. 

Two things I can think of:

1. Are you using Elixir 1.4? 
2. Have you created the event store database?

```console
MIX_ENV=test mix event_store.create
```

**Comment by slashdotdash** [comment]
@akeating I've added a "[Getting started](https://github.com/slashdotdash/conduit#getting-started)" section to the README now. Hopefully that will help to guide you.

**Comment by akeating** [comment]
ah that's really close to what I did. I had manually created the event_store tables instead of using `mix event_store.create`. Presumably that's an important distinction. Tests are passing now. I am looking forward to taking a closer look now that I'm all setup. Thanks.

**Comment by slashdotdash** [comment]
Great, glad to hear you're up and running.

**Comment by sardaukar** [comment]
I'm still having this issue :| 

```
=INFO REPORT==== 18-Nov-2017::18:00:08 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application eventstore: EventStore.Application.start(:normal, []) returned an error: shutdown: failed to start child: EventStore.Publisher
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in EventStore.Storage.QueryLatestEventNumber.handle_response/1
            (eventstore) lib/event_store/storage/query_latest_event_number.ex:11: EventStore.Storage.QueryLatestEventNumber.handle_response({:error, %Postgrex.Error{connection_id: 1706, message: nil, postgres: %{code: :undefined_table, file: "parse_relation.c", line: "1160", message: "relation \"event_counter\" does not exist", pg_code: "42P01", position: "26", routine: "parserOpenTable", severity: "ERROR", unknown: "ERROR"}}})
            (eventstore) lib/event_store/publisher.ex:26: EventStore.Publisher.start_link/1
            (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:348: :supervisor.start_children/3
            (stdlib) supervisor.erl:314: :supervisor.init_children/2
            (stdlib) gen_server.erl:328: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

I ran `MIX_ENV=test mix event_store.create` and `MIX_ENV=test mix do ecto.create, ecto.migrate` but I don't get the migrations output for the `test` env like I do for the `dev` one, but did get `The EventStore database has been created.` for the event store create command.

Not sure what I'm doing wrong...

**Comment by slashdotdash** [comment]
You also need to run: `MIX_ENV=test mix event_store.init`

**Comment by sardaukar** [comment]
That fixed it, thanks!
