### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by debonair** [slashdotdash/conduit#2]
CORS is not enabled, I am having an issue sending requests using the react fronted you recommended in your README.md

**Comment by slashdotdash** [comment]
Sorry, I had a local only branch with the changes required to support front-end requests using the [cors_plug](https://github.com/mschae/cors_plug) library.

Now merged into the `master` branch.

**Comment by slashdotdash** [comment]
The back end API is still incomplete, so when you browse the website certain parts won't yet work. 

Right now you can:

1. Sign up, logout, sign in.
2. Publish articles.
3. Favourite articles.

Additional features are work in progress!

**Comment by debonair** [comment]
Shoot! you beat me to it! Was just about to submit my pull request. 
Anyway, thanks will be following this repo very closely :)
