### ISSUE TITLE
Duplication of fields throughout the code

### ISSUE THREAD

**Issue by Yamilquery** [slashdotdash/conduit#21]
When we create a CRUD system usually we just need to define the fields in the `migrations` and `schemas` and that's it, but when we do CQRS (at least in this example) we need to define the same fields in:

- View
- Aggregates
- Commands
- Events
- Projections (*Ecto Schemas*)
- Projectors
- Migrations

I don't know if do in this way is a good approach because when we need to make a change in a single field we need to modify all those parts of the code, which sometimes is very complicated.

I know, CQRS has a lot of benefits comparing with CRUD, but I was wondering if this is the best way to do that.

Could you tell me if is this a good approach or we can do something to reduce the number of repeated fields definitions around the code?

**Comment by slashdotdash** [comment]
CQRS is usually best implemented for complex domains, not just CRUD based data manipulation. 

That said, you can often use a few tricks to reduce the amount of boilerplate:

- Use `struct(Foo, Map.from_struct(bar))` to easily copy fields from commands to events to aggregate state and projections. 
- Implement domain-specific macros to define commands/events/projections (such as [Commanded Messaging](https://github.com/trbngr/commanded_messaging)).
