### ISSUE TITLE
Remove `presence` from UpdateUser Command

### ISSUE THREAD

**Issue by hl** [slashdotdash/conduit#4]
Hey Ben, first off, great work!

I think these two lines can be removed in the command `UpdateUser` so they won't be mandatory when updating an existing user

https://github.com/slashdotdash/conduit/blob/master/lib/conduit/accounts/commands/update_user.ex#L21

https://github.com/slashdotdash/conduit/blob/master/lib/conduit/accounts/commands/update_user.ex#L27

**Comment by slashdotdash** [comment]
Yes, those fields should be made optional. Thanks for the feedback.
